#!/usr/bin/env bash
#This script can automat an installation of nginx on a web server

sudo apt update -y
sudo apt install nginx -y
echo "<h1>Holberton School</h1>" | sudo tee /var/www/html/index.nginx-debian.html > /dev/null
sudo service nginx restart
